#! /bin/sh

# Write EEPROM, ATMEL controller and play a test tone

OUT=/dev/tty1

case "$1" in
    start)
	i2c=`cat /boot/config.txt | grep i2c-gpio`
        if [ "$i2c" == "" ]; then
           echo "dtoverlay=i2c-gpio" >> /boot/config.txt
	   echo "dtparam=i2c_gpio_sda=0" >> /boot/config.txt
	   echo "dtparam=i2c_gpio_scl=1" >> /boot/config.txt
        fi

	# Program EEPROM
        PATH=$PATH:/opt/hifiberry/contrib
        export PATH
        /opt/hifiberry/contrib/hbflash.sh -w -f=/opt/hifiberry/contrib/amp3.eep -t=24c32

	echo "Programming micro-controller"  > $OUT
	pyupdi -c /dev/ttyAMA0 -d mega808 -f /opt/hifiberry/contrib/amp3_firmware.hex >> $OUT
	if [ $? != 0 ]; then
	   echo "Failed to program board"
	fi
	amixer sset Digital 72%
        play -n synth 60 sine 1000  &

	;;
    stop)
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

